### ISSUE TITLE
Is there anything that can be done to prevent ISP interference in osbuddy loading?

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#141]
I see people every day with issue loading client or with client being out of date. Osrs update days where a client update are required cause a spike in this. A large majority are from australia/nz but this happens to players from all over.

Could the cdn servers at least be switched to https? I think that will likely stop most of these network issues. Asking players to use a vpn always seems to work. Sadly not all are skilled enough to do so.

**Comment by NoEffex** [comment]
If they switch their default world it _should_ have an impact. The CDN can't really be switched to HTTPS due to costs but we might be able to work around it some other way (*note: we do signature checking on everything to ensure there was no MitM action*). If it is an issue downloading the OSRS client, we can't really work around that because we don't offer the download ourselves.

Side note: we've just started doing a login queue that should help with connectivity issues on update day.

**Comment by rsbfox** [comment]
Thanks. I will try asking some people with issue loading osbuddy to try that. I will also have them download some files from rsbuddy to check that they are correct.
