### ISSUE TITLE
Option Reorder: Missing bankers

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#164]
- Bankers
- [x] Ghost banker
- [x] Gnome banker
- [x] Sirsal Banker
- [x] Nardah Banker
- [x] TzHaar-Ket-Zuh
- [x] TzHaar-Ket-Yil
- [x] Financial Seer
- [x] Financial Wizard
- Unique bankers - If you want to swap them as well.
- [ ] \u0027Bird\u0027s-Eye\u0027 Jack
- [x] Gundai
- [ ] Squire //n.b. ID 1764 Other squire without bank option.
- [ ] Jade
- [x] Fadli
- [x] Odovacar
- [x] Magnus Gram
- [x] Jumaane
- [x] Eniola

**Comment by NoEffex** [comment]
For efficiency reasons the casing of the name matters. Is it 'Ghost banker' or is it 'Ghost Banker'? likewise with gnome banker

**Comment by rsbfox** [comment]
All are exact names. Yes it bothered me also that they are not consistent.

**Comment by rsbfox** [comment]
Jade is the warrior guild banker.

Sorry, made a mistake with jack. His name changes slightly when he becomes a banker? Weird.
**Before quest**
```
  {
    "id": 3861,
    "name": "\u0027Birds-Eye\u0027 Jack",
    "level": 0,
    "actions": [
      "Talk-to"
    ]
  },
```
**After quest**
```
  {
    "id": 3472,
    "name": "\u0027Bird\u0027s-Eye\u0027 Jack",
    "level": 0,
    "actions": [
      "Talk-to",
      "Bank",
      "Collect"
    ]
  },
```

Also 

Financial Seer & Financial Wizard are deadman only and have another option. `Deposit-box`

**Comment by rsbfox** [comment]
Sorry. Listed Eniola but option reorder should not mess with him. He is Zmi banker. Already is a left-click banker.

**Comment by UhWatchMe** [comment]
Since we have to check them again as requested by Pacman, I think it's handy to know which ones are checked starting from 26 August 2017.

I am unable to do following bankers

- Nardah Banker (I do not have Contact! Quest completed)
- Tzhaar-Ket-Yil (I do not have a firecape I assume that's the requirement.)
- Jumaanee (I do not have Monkey Madness 2 completed.)

- Bankers
- [x] Ghost banker
- [x] Gnome banker
- [x] Sirsal Banker
- [x] Nardah Banker
- [x] TzHaar-Ket-Zuh
- [x] TzHaar-Ket-Yil
- [x] Financial Seer
- [x] Financial Wizard
- Unique bankers - If you want to swap them as well.
- [x] \u0027Bird\u0027s-Eye\u0027 Jack
- [x] Gundai
- [ ] Squire //n.b. ID 1764 Other squire without bank option.
Appears to be broken
![squire](http://i.imgur.com/qqpx3hm.png)
- [ ] Jade
Appears to be broken
![Jade](http://i.imgur.com/EeknVw1.png)
- [x] Fadli
- [x] Odovacar
- [x] Magnus Gram
- [x] Jumaane
- [x] Eniola
- [x] Emerald Benedict
