### ISSUE TITLE
macOS retina hidpi scaling is worse on osbuddy compared to other clients

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#201]
Osbuddy on right.
![image](https://user-images.githubusercontent.com/30416150/29498442-7cc27d82-85ca-11e7-9664-dac6b9fd2e22.png)

There is clearly some poor upscaling being done.

**Comment by rsbfox** [comment]
Fix is to change these in info.plist to no.
![image](https://user-images.githubusercontent.com/30416150/29498616-2bdfc92a-85ce-11e7-953a-da1a26aea077.png)

Also replacing plugin folder java with latest from jetbrains improves performance.

**Comment by NoEffex** [comment]
I'll release a new app on the website soon (TM). The only thing about the app is due to the fact it's actually a directory auto-updating it is quite difficult and maintain a version on the app store is even more difficult due to the fact that we constantly update ourselves and they aren't fond of that.

**Comment by rsbfox** [comment]
Thanks. I think #140 could use some fixes most of all. I pinned shellscript to #support that updates java to latest and fixes hidpi issue for now.

**Comment by rsbfox** [comment]
Merged into #140
