### ISSUE TITLE
Really bad font display on Linux client

### ISSUE THREAD

**Issue by SapiensAnatis** [rsbmatt/OSBuddy#223]
I'm unsure if this is a system config issue (I have had some issues with fonts) but the text in the options and login window looks really bad.

![image](https://user-images.githubusercontent.com/5047192/29688439-a98fd94a-8917-11e7-8ccf-44b6b7538503.png)

As you can see, the text at the top of the title bars doesn't really suffer from this issue, which is strange. In-game overlay text is also fine; it's just the login prompt (for OSBuddy, not RuneScape) and options menu that have this issue.

I'm using i3 with Arch.

**Comment by rsbfox** [comment]
Sorry. OSBuddy has no control of font rendering Java uses for some text. So this isn't a bug OSBuddy can fix. https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts

I did observed this myself on Arch kde but gave up trying to fix it. Looked fine on gnome though.
Post on https://discord.gg/osbuddy #support about this and ask matthew#9476 to help.

He uses Arch and knows about what causes this. The reason some text is fine is because swing and awt do it differently.
