### ISSUE TITLE
Opacity option for overlays

### ISSUE THREAD

**Issue by azeruk** [rsbmatt/OSBuddy#31]
Would be nice since I don't really like the brown stuff on the overlays 
![image](https://user-images.githubusercontent.com/30416150/28589337-9f2c6d9e-714b-11e7-9c76-fcf866751f1e.png)

Also making them moveable/resizeable would be so nice.

**Comment by NoEffex** [comment]
Allowing everything to be movable generally isn't going to be feasible nor desirable (see: NIS) due to the amount of work required to abstract such a system while still making it look nice by default. Making the background color changable isn't overly difficult however due to the fact that we did the work to centralise which colors it uses a while ago.
