### ISSUE TITLE
More suggestions

### ISSUE THREAD

**Issue by Jalopyy** [rsbmatt/OSBuddy#375]
1) A !calc chat command. Yes, I realize that there's a calculator module but it's way to type something like !calc 50*389 than to switch modules and click that all in manually. Having it support suffixes for k/m (for thousand and million) would be nice too.
2) Expand idle alerts for skilling to fishing, smithing (smelting and actual smithing), fletching, cooking, crafting, herblore, woodcutting. I miss this from Runeloader since while playing on my laptop I prefer to tab out than watch the grass grow.
3) Add flax->bowstring exchange to daily reminder module.

**Comment by rsbfox** [comment]
1. Too much spam in chat. 
2. Being done.
3. I'll make a separate issue for that specific idea.

Thanks.

**Comment by rsbfox** [comment]
Actually I'll need to ask @rsbmatt about that reminder before making issue. Bstaffs have an object in game that changes form when bstaffs are available. That is likely a player variable.

Tears of guthix should be able to be added because quest menu changes. But most other dailies require you to talk to an npc to know when.
